# configs/experiment.yaml
includes:
  - datasets/wdbc.yaml            # escolha 1 dataset
  - devices/amp_wdbc.yaml         # escolha 1 device compatível com o FM e nº de features
  - feature_maps/amplitude.yaml   # escolha um Feature Map
  - ansatz/ansatz5_d20.yaml        # escolha 1 ansatz (layer_1..layer_6) e profundidade
  - optimizers/ga_50.yaml         # escolha 1 otimizador (GA/Adam/Nesterov)

meta:
  project_name: "qml-ga-project"
  notes: "Execução padrão (WDBC + Amplitude + layer_5 d=20 + GA@50)"

seed: 42

output:
  base_dir: "runs"
  save_specs: false        # true para salvar qml.specs do 1º fold
